### ISSUE TITLE
Receive 401 Unauthorized

### ISSUE THREAD

**Issue by jehaslam** [MatthiWare/YahooFinance.Core#11]
I receive a 401 unauthorized.
I have had this working perfectly, but after a day it started giving me the 401

Research suggests you need to add a cookie and crumb refresh:
https://stackoverflow.com/questions/44105187/error-in-downloading-csv-from-new-yahoo-finance-historical-data

**Comment by jehaslam** [comment]
If a stock history has "null" instead of decimal values, the csv parser throws.
You can test this with stock "ACAMU". I was looking at one year of history.

This could be fixed by adding these converters to the client:

public class NullDecimalConverter : DefaultTypeConverter
    {
        public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
        {
            bool hasPassed = decimal.TryParse(text, out decimal val);
            return hasPassed ? val : new Decimal(-99999.999);
        }
    }

 public class NullIntConverter : DefaultTypeConverter
    {
        public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
        {
            bool hasPassed = int.TryParse(text, out int val);
            return hasPassed ? val : -99999;
        }
    }

**Comment by Matthiee** [comment]
Hi @jehaslam 

I can reproduce the issue with the ticker symbol "ACAMU". 

```
Message: 
    Error in response: CsvHelper.TypeConversion.TypeConverterException: The conversion cannot be performed.
        Text: 'null'
        MemberType: System.Decimal
        TypeConverter: 'CsvHelper.TypeConversion.DecimalConverter'
       at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
       at CsvHelper.TypeConversion.DecimalConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
       at lambda_method(Closure )
       at CsvHelper.Expressions.RecordCreator.Create[T]()
       at CsvHelper.Expressions.RecordManager.Create[T]()
       at CsvHelper.CsvReader.GetRecords[T]()+MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at MatthiWare.YahooFinance.Core.Http.ApiClient.ExecuteCsvAsync[ReturnType](String urlPattern, NameValueCollection nvc, QueryStringBuilder qsb, CancellationToken cancellationToken) in D:\Source\Repos\YahooFinance.Core\YahooFinance.Core\YahooFinance.Core\Core\Http\ApiClient.cs:line 66
    Expected: False
    Actual:   True
  Stack Trace: 
    ApiResponseExtensions.AssertValidResponse[T](IApiResponse`1 response) line 12
    HistoryTests.GetPricesWorksCorrectly(String symbol) line 57
    --- End of stack trace from previous location where exception was thrown ---
```

**Comment by Matthiee** [comment]
Hi @jehaslam a new nuget package is available that fixes your issue.
